### ISSUE TITLE
Error running "npm run build"

### ISSUE THREAD

**Issue by thinkmaps** [fuzzc0re/electron-svelte-typescript#10]
I get follwing error, when I run "npm run build"
```
tsconfigSvelteJSON.compilerOptions.sourceMap = false;
TypeError: Cannot set property 'sourceMap' of undefined
    at generateProdTSConfig (<MYFILEPATH>\scripts\preBuild.js:31:48)
    at Object.<anonymous> (<MYFILEPATH>\scripts\preBuild.js:50:3)
```

**Comment by DiegoBM** [comment]
Same here

**Comment by moniker** [comment]
Because `compilerOptions` doesn't exist within the `tsconfig.electron.json` and `tsconfig.svelte.json` files and the `extends` syntax is obviously only for typescript (here we're just using pure JSON files), I just added these lines to line 30 to default the `compilerOptions` to an empty object should it not exist and `npm run build` works fine:

```
  tsconfigSvelteJSON.compilerOptions = tsconfigSvelteJSON.compilerOptions || {};
  tsconfigElectronJSON.compilerOptions = tsconfigElectronJSON.compilerOptions || {};
```
